# Assignment 0
# 1 Numpy
## Name : Darpan Gaur
## Roll No : CO21BTECH11004

In [7]:
# (a)
import numpy as np

In [2]:
# (b) Create a null vector of size 10, and output the vector to the terminal.
null_vector = np.zeros(10)
print(null_vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
# (c) Create a null vector of size 10 but the fifth value which is 1.
null_vector = np.zeros(10)
null_vector[4] = 1
print(null_vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [4]:
# (d) Reverse a vector (first element becomes last).
vector = np.arange(10)
print(f"Original vector: {vector}")
reversed_vector = vector[::-1]
print(f"Reversed vector: {reversed_vector}")

Original vector: [0 1 2 3 4 5 6 7 8 9]
Reversed vector: [9 8 7 6 5 4 3 2 1 0]


In [5]:
# (e) Create an n × n array with checkerboard pattern of zeros and ones.
n = 8
checkerboard = np.zeros((n, n))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [7]:
# (f) Given an n × n array, sort the rows of array according to mth column of array.
n = 5
m = 2
array = np.random.randint(0, 23, (n, n))
print(f"Original array:\n{array}")
sorted_array = array[array[:, m].argsort()]
print(f"Sorted array:\n{sorted_array}")


Original array:
[[ 6  4  5 21 18]
 [ 3  8 12  7  0]
 [12 14  0  0 21]
 [ 7  1  8 18  8]
 [ 8  7  7 12  5]]
Sorted array:
[[12 14  0  0 21]
 [ 6  4  5 21 18]
 [ 8  7  7 12  5]
 [ 7  1  8 18  8]
 [ 3  8 12  7  0]]


In [8]:
# (g) Create an n × n array with (i + j)th element equal to i + j.
n = 5
array = np.fromfunction(lambda i, j: i + j, (n, n))
print(array)

[[0. 1. 2. 3. 4.]
 [1. 2. 3. 4. 5.]
 [2. 3. 4. 5. 6.]
 [3. 4. 5. 6. 7.]
 [4. 5. 6. 7. 8.]]


In [12]:
# (h) Consider a (6, 7, 8) shape array, what is the index (x, y, z) of the 100th element (of the entire structure)?
shape = (6, 7, 8)
index = np.unravel_index(100, shape)
print(f"x, y, z = {index}")

x, y, z = (1, 5, 4)


In [8]:
# (i) Multiply a 5 × 3 matrix by a 3 × 2 matrix (real matrix product).
matrix1 = np.random.randint(0, 10, (5, 3))
matrix2 = np.random.randint(0, 10, (3, 2))
product = np.dot(matrix1, matrix2)
print(f"Matrix 1:\n{matrix1}")
print(f"Matrix 2:\n{matrix2}")
print(f"Product:\n{product}")

Matrix 1:
[[7 1 6]
 [7 4 9]
 [0 5 3]
 [5 1 4]
 [5 5 1]]
Matrix 2:
[[1 6]
 [8 1]
 [4 2]]
Product:
[[39 55]
 [75 64]
 [52 11]
 [29 39]
 [49 37]]


In [9]:
# (j) Create a random vector of size 10 and replace the maximum value by 0.
vector = np.random.randint(0, 100, 10)
print(f"Original vector: {vector}")
max_index = np.argmax(vector)
vector[max_index] = 0
print(f"Vector with maximum value replaced by 0: {vector}")

Original vector: [91 14 28 99 30 43 33 16 57 47]
Vector with maximum value replaced by 0: [91 14 28  0 30 43 33 16 57 47]


In [10]:
# (k) How to find the closest value (to a given scalar) in a vector?
vector = np.random.randint(0, 100, 10)
scalar = 50
closest_value = vector[np.abs(vector - scalar).argmin()]
print(f"Vector: {vector}")
print(f"Scalar: {scalar}")
print(f"Closest value to the scalar: {closest_value}")

Vector: [94 41 25 56 93 67  6 20 64 43]
Scalar: 50
Closest value to the scalar: 56


In [16]:
# (l) Subtract the mean of each row from each corresponding row of a matrix.
matrix = np.random.random((5, 3))
print(f"Original matrix:\n{matrix}")
mean = matrix.mean(axis=1)
matrix -= mean[:, np.newaxis]
print(f"Matrix with mean of each row subtracted from corresponding row:\n{matrix}")

Original matrix:
[[0.49385559 0.15427036 0.04067541]
 [0.75470963 0.66203253 0.37369755]
 [0.48988025 0.57633341 0.18282969]
 [0.10796426 0.48406802 0.2271423 ]
 [0.07442291 0.05211021 0.06351876]]
Matrix with mean of each row subtracted from corresponding row:
[[ 2.64255140e-01 -7.53300971e-02 -1.88925043e-01]
 [ 1.57896392e-01  6.52192964e-02 -2.23115688e-01]
 [ 7.35324700e-02  1.59985624e-01 -2.33518094e-01]
 [-1.65093935e-01  2.11009829e-01 -4.59158937e-02]
 [ 1.10722878e-02 -1.12404198e-02  1.68131970e-04]]


In [19]:
# (m) Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices - you should consider it only once)?
vector = np.random.randint(0, 10, 10)
print(f"Original vector: {vector}")
indices = np.random.randint(0, 10, 5)
print(f"Indices: {indices}")
vector += np.bincount(indices, minlength=len(vector))
print(f"Vector with 1 added to each element indexed by the second vector: {vector}")


Original vector: [6 6 5 9 2 6 2 7 7 7]
Indices: [2 0 8 5 7]
Vector with 1 added to each element indexed by the second vector: [7 6 6 9 2 7 2 8 8 7]


In [20]:
# (n) How to find the most frequent value in an array?
array = np.random.randint(0, 10, 100)
print(f"Array: {array}")
most_frequent_value = np.bincount(array).argmax()
print(f"Most frequent value: {most_frequent_value}")

Array: [6 8 3 2 9 1 1 4 7 9 9 2 9 8 9 3 4 7 6 9 2 1 0 9 2 7 1 2 9 4 6 7 3 7 6 3 9
 3 6 7 3 4 8 2 1 9 9 7 4 9 8 8 1 7 8 0 0 9 5 8 6 2 0 7 3 1 8 6 1 5 6 4 8 4
 0 9 8 2 6 7 8 7 5 9 6 4 5 1 2 9 2 8 9 2 5 1 8 2 0 0]
Most frequent value: 9


In [21]:
# (o) Extract all the contiguous 3 × 3 blocks from a random 10 × 10 matrix.
matrix = np.random.randint(0, 10, (10, 10))
print(f"Original matrix:\n{matrix}")
n = 3
blocks = np.lib.stride_tricks.sliding_window_view(matrix, (n, n))
print(f"3x3 blocks:\n{blocks}")

Original matrix:
[[7 6 4 6 4 5 1 0 0 1]
 [3 1 0 1 9 5 7 7 5 8]
 [1 7 6 1 6 2 9 5 2 7]
 [0 2 4 5 8 7 2 7 9 3]
 [1 8 0 7 0 3 5 1 1 1]
 [0 6 7 6 3 4 2 1 0 9]
 [6 1 0 8 7 3 6 5 2 1]
 [2 0 3 1 9 3 6 2 3 0]
 [4 6 4 9 1 6 5 0 9 1]
 [9 5 9 1 4 9 6 2 8 9]]
3x3 blocks:
[[[[7 6 4]
   [3 1 0]
   [1 7 6]]

  [[6 4 6]
   [1 0 1]
   [7 6 1]]

  [[4 6 4]
   [0 1 9]
   [6 1 6]]

  [[6 4 5]
   [1 9 5]
   [1 6 2]]

  [[4 5 1]
   [9 5 7]
   [6 2 9]]

  [[5 1 0]
   [5 7 7]
   [2 9 5]]

  [[1 0 0]
   [7 7 5]
   [9 5 2]]

  [[0 0 1]
   [7 5 8]
   [5 2 7]]]


 [[[3 1 0]
   [1 7 6]
   [0 2 4]]

  [[1 0 1]
   [7 6 1]
   [2 4 5]]

  [[0 1 9]
   [6 1 6]
   [4 5 8]]

  [[1 9 5]
   [1 6 2]
   [5 8 7]]

  [[9 5 7]
   [6 2 9]
   [8 7 2]]

  [[5 7 7]
   [2 9 5]
   [7 2 7]]

  [[7 7 5]
   [9 5 2]
   [2 7 9]]

  [[7 5 8]
   [5 2 7]
   [7 9 3]]]


 [[[1 7 6]
   [0 2 4]
   [1 8 0]]

  [[7 6 1]
   [2 4 5]
   [8 0 7]]

  [[6 1 6]
   [4 5 8]
   [0 7 0]]

  [[1 6 2]
   [5 8 7]
   [7 0 3]]

  [[6 2 9]
   [8 7 2]
   [0 3 5]]

 

In [30]:
# (p) Compute the rank, trace and determinant of a matrix.
matrix = np.random.randint(0, 10, (3, 3))
print(f"Matrix:\n{matrix}")
rank = np.linalg.matrix_rank(matrix)
trace = np.trace(matrix)
determinant = np.linalg.det(matrix)
print(f"Rank: {rank}")
print(f"Trace: {trace}")
print(f"Determinant: {determinant}")

Matrix:
[[8 4 0]
 [1 2 3]
 [7 9 7]]
Rank: 3
Trace: 17
Determinant: -47.999999999999986
